import type { Contact, Message } from "./types"

export const initialContacts: Contact[] = [
  {
    id: "1",
    name: "Mehedi Ju",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "good job brother",
    lastMessageTime: new Date(2025, 4, 4, 12, 11),
    lastMessageStatus: "read",
    isOnline: true,
    lastSeen: new Date(),
    unreadCount: 0,
  },
  {
    id: "2",
    name: "Atiqur Rahman",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "Voice call",
    lastMessageTime: new Date(2025, 4, 4, 8, 43),
    isOnline: false,
    lastSeen: new Date(2025, 4, 4, 9, 15),
    unreadCount: 2,
  },
  {
    id: "3",
    name: "+880... (You)",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "Incoming again",
    lastMessageTime: new Date(2025, 4, 4, 7, 17),
    isOnline: false,
    lastSeen: new Date(2025, 4, 4, 7, 30),
    unreadCount: 0,
  },
  {
    id: "4",
    name: "Jaman Lu",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "Hii",
    lastMessageTime: new Date(2025, 4, 4, 11, 25),
    isOnline: true,
    lastSeen: new Date(),
    unreadCount: 1,
  },
  {
    id: "5",
    name: "Pantone Classic",
    avatar: "/placeholder.svg?height=200&width=200",
    lastMessage: "A. Rahman Khan...",
    lastMessageTime: new Date(2025, 4, 4, 9, 44),
    isOnline: false,
    lastSeen: new Date(2025, 4, 4, 10, 0),
    unreadCount: 0,
  },
]

export const initialMessages: Message[] = [
  {
    id: "msg1",
    content: "good job brother",
    timestamp: new Date(2025, 4, 4, 12, 11),
    senderId: "1",
    receiverId: "me",
    status: "read",
  },
  {
    id: "msg2",
    content: "timspark.com\nhttps://timspark.com/portfolio/microlearning-platform-for-education/\ntimspark.com",
    timestamp: new Date(2025, 4, 4, 12, 30),
    senderId: "1",
    receiverId: "me",
    status: "read",
  },
  {
    id: "msg3",
    content: "https://timspark.com/portfolio/microlearning-platform-for-education/",
    timestamp: new Date(2025, 4, 4, 13, 36),
    senderId: "1",
    receiverId: "me",
    status: "read",
  },
  {
    id: "msg4",
    content: "boss aita follow kore portfolio page crate koiren",
    timestamp: new Date(2025, 4, 4, 13, 37),
    senderId: "1",
    receiverId: "me",
    status: "read",
  },
  {
    id: "msg5",
    content: "val 3 ta project add kore si",
    timestamp: new Date(2025, 4, 4, 16, 53),
    senderId: "1",
    receiverId: "me",
    status: "read",
  },
  {
    id: "msg6",
    content: "Voice call\n1 min",
    timestamp: new Date(2025, 4, 4, 19, 32),
    senderId: "1",
    receiverId: "me",
    status: "read",
    type: "audio",
    attachments: ["/placeholder.svg?height=100&width=100"],
  },
  {
    id: "msg7",
    content: "Today",
    timestamp: new Date(2025, 4, 4, 20, 0),
    senderId: "system",
    receiverId: "system",
  },
  {
    id: "msg8",
    content: "Assalamualikum vai",
    timestamp: new Date(2025, 4, 4, 22, 20),
    senderId: "1",
    receiverId: "me",
    status: "read",
  },
  {
    id: "msg9",
    content: "ha, vai\nproject part dynamic sesh er dike",
    timestamp: new Date(2025, 4, 4, 22, 22),
    senderId: "me",
    receiverId: "1",
    status: "read",
  },
  {
    id: "msg10",
    content: "1 hour por responsive part dhorteci",
    timestamp: new Date(2025, 4, 4, 22, 22),
    senderId: "me",
    receiverId: "1",
    status: "read",
  },
  {
    id: "msg11",
    content: "Ok boss",
    timestamp: new Date(2025, 4, 4, 22, 25),
    senderId: "1",
    receiverId: "me",
    status: "read",
  },
  {
    id: "msg12",
    content: "pm2 restart den",
    timestamp: new Date(2025, 4, 4, 23, 16),
    senderId: "me",
    receiverId: "1",
    status: "read",
    reactions: [{ emoji: "👍", userId: "1" }],
  },
  {
    id: "msg13",
    content: "manual restart diye ai",
    timestamp: new Date(2025, 4, 4, 23, 19),
    senderId: "1",
    receiverId: "me",
    status: "read",
  },
  {
    id: "msg14",
    content: "kaj hoi ni vai",
    timestamp: new Date(2025, 4, 4, 23, 23),
    senderId: "1",
    receiverId: "me",
    status: "read",
    replyTo: {
      id: "msg12",
      content: "pm2 restart den",
      senderId: "me",
    },
  },
  {
    id: "msg15",
    content: "manually build diye restart den",
    timestamp: new Date(2025, 4, 4, 23, 28),
    senderId: "me",
    receiverId: "1",
    status: "read",
  },
  {
    id: "msg16",
    content: "ok boss",
    timestamp: new Date(2025, 4, 4, 23, 38),
    senderId: "1",
    receiverId: "me",
    status: "read",
  },
  {
    id: "msg17",
    content: "Check out these screenshots",
    timestamp: new Date(2025, 4, 5, 10, 15),
    senderId: "me",
    receiverId: "1",
    status: "read",
    type: "media",
    attachments: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
  },
]
